segundos = int(input('Digite os segundos inteiros: '))
print(f'{segundos} segundos equivale a {segundos // 3600} horas')
print(f'{segundos} segundos equivale a {segundos // 60}')
print(f'{segundos} segunos')
print(f'Formando {segundos//3600}:{segundos//60}:{segundos} ')
